/**
 * AppWizard Styles
 * Unified style constants for both page and modal modes
 */

const SF_PRO_TEXT = "-apple-system, BlinkMacSystemFont, 'SF Pro Text', sans-serif";
const SF_PRO_DISPLAY = "-apple-system, BlinkMacSystemFont, 'SF Pro Display', sans-serif";

// ---------------------------------------------------------------------------
// Shared base styles
// ---------------------------------------------------------------------------

export const baseStyles = {
  spinner: {
    width: 32,
    height: 32,
    border: '3px solid rgba(0, 0, 0, 0.1)',
    borderTopColor: '#0071e3',
    borderRadius: '50%',
    animation: 'spin 0.8s linear infinite',
    marginBottom: 12,
  },
  loadingState: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 48,
    color: '#86868b',
  },
  errorState: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    gap: 12,
    padding: 32,
    color: '#ff3b30',
    textAlign: 'center' as const,
  },
  progressContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    padding: '12px 24px',
    backgroundColor: '#f5f5f7',
  },
  progressBar: {
    flex: 1,
    height: 6,
    backgroundColor: 'rgba(0, 113, 227, 0.2)',
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#0071e3',
    borderRadius: 3,
    transition: 'width 0.3s ease',
  },
  progressText: {
    fontSize: 12,
    color: '#86868b',
    fontFamily: SF_PRO_TEXT,
    minWidth: 80,
    textAlign: 'right' as const,
  },
  appInfo: {
    display: 'flex',
    alignItems: 'center',
    gap: 16,
    padding: 16,
    backgroundColor: '#ffffff',
    borderRadius: 12,
    marginBottom: 24,
    boxShadow: '0 1px 3px rgba(0, 0, 0, 0.04)',
  },
  appIcon: {
    width: 56,
    height: 56,
    borderRadius: 12,
    backgroundColor: '#f5f5f7',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  appIconImg: {
    width: '100%',
    height: '100%',
    objectFit: 'contain' as const,
  },
  appMeta: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 4,
  },
  appVersion: {
    fontSize: 15,
    fontWeight: 600,
    color: '#1d1d1f',
    fontFamily: SF_PRO_DISPLAY,
  },
  appTrain: {
    fontSize: 13,
    color: '#86868b',
    fontFamily: SF_PRO_TEXT,
  },
  searchContainer: {
    marginBottom: 20,
  },
  searchWrapper: {
    display: 'flex',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 10,
    padding: '10px 14px',
    gap: 10,
    border: '1px solid rgba(0, 0, 0, 0.08)',
  },
  searchIcon: {
    flexShrink: 0,
  },
  searchInput: {
    flex: 1,
    border: 'none',
    background: 'transparent',
    fontSize: 14,
    outline: 'none',
    color: '#1d1d1f',
    fontFamily: SF_PRO_TEXT,
  },
  header: {
    display: 'flex',
    alignItems: 'flex-start',
    padding: '24px 24px 20px',
    borderBottom: '1px solid rgba(0, 0, 0, 0.08)',
    backgroundColor: '#ffffff',
  },
  headerInfo: {
    flex: 1,
  },
  title: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    fontSize: 20,
    fontWeight: 700,
    color: '#1d1d1f',
    margin: 0,
    fontFamily: SF_PRO_DISPLAY,
  },
  subtitle: {
    fontSize: 13,
    color: '#86868b',
    margin: '6px 0 0 30px',
    fontFamily: SF_PRO_TEXT,
  },
  sectionTitleOutside: {
    fontSize: 15,
    fontWeight: 700,
    color: '#1d1d1f',
    marginBottom: 8,
    fontFamily: SF_PRO_DISPLAY,
  },
  formGroup: {
    marginBottom: 20,
  },
  label: {
    display: 'block',
    fontSize: 13,
    fontWeight: 600,
    color: '#1d1d1f',
    marginBottom: 6,
    fontFamily: SF_PRO_TEXT,
  },
  required: {
    color: '#ff3b30',
    marginLeft: 2,
  },
  fieldDescription: {
    fontSize: 12,
    color: '#86868b',
    margin: '0 0 8px 0',
    fontFamily: SF_PRO_TEXT,
  },
  fieldHint: {
    fontSize: 11,
    color: '#86868b',
    margin: '4px 0 0 0',
    fontFamily: SF_PRO_TEXT,
  },
  input: {
    width: '100%',
    padding: '10px 14px',
    fontSize: 15,
    border: '1px solid rgba(0, 0, 0, 0.12)',
    borderRadius: 8,
    backgroundColor: '#ffffff',
    color: '#1d1d1f',
    outline: 'none',
    fontFamily: SF_PRO_TEXT,
    boxSizing: 'border-box' as const,
    transition: 'border-color 0.2s ease',
  },
  inputDisabled: {
    backgroundColor: '#f5f5f7',
    cursor: 'not-allowed',
  },
  inputError: {
    width: '100%',
    padding: '10px 14px',
    fontSize: 15,
    border: '1px solid #ff3b30',
    borderRadius: 8,
    backgroundColor: '#ffffff',
    color: '#1d1d1f',
    outline: 'none',
    fontFamily: SF_PRO_TEXT,
    boxSizing: 'border-box' as const,
    transition: 'border-color 0.2s ease',
  },
  select: {
    width: '100%',
    padding: '10px 14px',
    fontSize: 15,
    border: '1px solid rgba(0, 0, 0, 0.12)',
    borderRadius: 8,
    backgroundColor: '#ffffff',
    color: '#1d1d1f',
    outline: 'none',
    fontFamily: SF_PRO_TEXT,
    boxSizing: 'border-box' as const,
    cursor: 'pointer',
  },
  selectError: {
    width: '100%',
    padding: '10px 14px',
    fontSize: 15,
    border: '1px solid #ff3b30',
    borderRadius: 8,
    backgroundColor: '#ffffff',
    color: '#1d1d1f',
    outline: 'none',
    fontFamily: SF_PRO_TEXT,
    boxSizing: 'border-box' as const,
    cursor: 'pointer',
  },
  checkboxLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    fontSize: 14,
    color: '#1d1d1f',
    cursor: 'pointer',
    fontFamily: SF_PRO_TEXT,
  },
  checkbox: {
    width: 18,
    height: 18,
    cursor: 'pointer',
  },
  sectionFields: {
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
    padding: 16,
    backgroundColor: '#fafafa',
    borderRadius: 12,
  },
  listContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
  },
  listEmpty: {
    fontSize: 13,
    color: '#86868b',
    fontFamily: SF_PRO_TEXT,
  },
  listItem: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 8,
    padding: 12,
    backgroundColor: '#f5f5f7',
    borderRadius: 8,
  },
  listItemContent: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
  },
  listItemField: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  },
  listItemLabel: {
    fontSize: 12,
    fontWeight: 600,
    color: '#1d1d1f',
    fontFamily: SF_PRO_TEXT,
  },
  listItemSimple: {
    flex: 1,
  },
  listItemInput: {
    width: '100%',
    padding: '8px 12px',
    fontSize: 14,
    border: '1px solid rgba(0, 0, 0, 0.12)',
    borderRadius: 6,
    backgroundColor: '#ffffff',
    color: '#1d1d1f',
    outline: 'none',
    fontFamily: SF_PRO_TEXT,
    boxSizing: 'border-box' as const,
  },
  listItemDelete: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 28,
    height: 28,
    border: 'none',
    backgroundColor: 'rgba(0, 0, 0, 0.05)',
    borderRadius: 6,
    cursor: 'pointer',
    color: '#86868b',
    transition: 'all 0.2s ease',
    flexShrink: 0,
  },
  listAddButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    padding: '8px 14px',
    fontSize: 13,
    fontWeight: 500,
    color: '#0071e3',
    backgroundColor: 'rgba(0, 113, 227, 0.08)',
    border: 'none',
    borderRadius: 6,
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    fontFamily: SF_PRO_TEXT,
  },
  dictContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
    padding: 12,
    backgroundColor: '#f5f5f7',
    borderRadius: 8,
  },
  nestedFormGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  },
  nestedFormGroupError: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
    padding: 8,
    borderRadius: 6,
    border: '1px solid #ff3b30',
    backgroundColor: 'rgba(255, 59, 48, 0.05)',
  },
  nestedLabel: {
    display: 'block',
    fontSize: 12,
    fontWeight: 600,
    color: '#1d1d1f',
    fontFamily: SF_PRO_TEXT,
  },
  nestedDescription: {
    fontSize: 11,
    color: '#86868b',
    margin: '0 0 6px 0',
    fontFamily: SF_PRO_TEXT,
  },
  submitButtonDisabled: {
    opacity: 0.6,
    cursor: 'not-allowed',
  },
  buttonSpinner: {
    width: 14,
    height: 14,
    border: '2px solid rgba(255, 255, 255, 0.3)',
    borderTopColor: '#ffffff',
    borderRadius: '50%',
    animation: 'spin 0.8s linear infinite',
  },
};

// ---------------------------------------------------------------------------
// Page mode styles
// ---------------------------------------------------------------------------

export const pageStyles = {
  container: {
    height: '100%',
    display: 'flex',
    flexDirection: 'column' as const,
    backgroundColor: '#f5f5f7',
  },
  header: baseStyles.header,
  headerInfo: baseStyles.headerInfo,
  title: baseStyles.title,
  subtitle: baseStyles.subtitle,
  progressContainer: baseStyles.progressContainer,
  progressBar: baseStyles.progressBar,
  progressFill: baseStyles.progressFill,
  progressText: baseStyles.progressText,
  form: {
    flex: 1,
    padding: 24,
  },
  loadingState: baseStyles.loadingState,
  spinner: baseStyles.spinner,
  errorState: baseStyles.errorState,
  appInfo: baseStyles.appInfo,
  appIcon: baseStyles.appIcon,
  appIconImg: baseStyles.appIconImg,
  appMeta: baseStyles.appMeta,
  appVersion: baseStyles.appVersion,
  appTrain: baseStyles.appTrain,
  searchContainer: baseStyles.searchContainer,
  searchWrapper: {
    ...baseStyles.searchWrapper,
    backgroundColor: '#ffffff',
    border: '1px solid rgba(0, 0, 0, 0.08)',
  },
  searchIcon: baseStyles.searchIcon,
  searchInput: baseStyles.searchInput,
  submitContainer: {
    display: 'flex',
    justifyContent: 'flex-end',
    padding: '16px 0',
    marginTop: 24,
    borderTop: '1px solid rgba(0, 0, 0, 0.08)',
  },
  submitButton: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '12px 32px',
    fontSize: 15,
    fontWeight: 600,
    color: '#ffffff',
    backgroundColor: '#0071e3',
    border: 'none',
    borderRadius: 10,
    cursor: 'pointer',
    fontFamily: SF_PRO_TEXT,
    transition: 'all 0.2s ease',
    boxShadow: '0 4px 12px rgba(0, 113, 227, 0.3)',
  },
  submitButtonDisabled: baseStyles.submitButtonDisabled,
  buttonSpinner: baseStyles.buttonSpinner,
};

// ---------------------------------------------------------------------------
// Modal mode styles
// ---------------------------------------------------------------------------

export const modalStyles = {
  overlay: {
    position: 'fixed' as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
  },
  modal: {
    width: 640,
    maxHeight: '90vh',
    backgroundColor: '#ffffff',
    borderRadius: 16,
    boxShadow: '0 20px 60px rgba(0, 0, 0, 0.3)',
    display: 'flex',
    flexDirection: 'column' as const,
    overflow: 'hidden',
  },
  header: baseStyles.header,
  headerInfo: baseStyles.headerInfo,
  title: baseStyles.title,
  subtitle: baseStyles.subtitle,
  closeButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 32,
    height: 32,
    border: 'none',
    backgroundColor: 'rgba(0, 0, 0, 0.05)',
    borderRadius: 8,
    cursor: 'pointer',
    color: '#86868b',
    transition: 'all 0.2s ease',
  },
  progressContainer: baseStyles.progressContainer,
  progressBar: baseStyles.progressBar,
  progressFill: baseStyles.progressFill,
  progressText: baseStyles.progressText,
  form: {
    flex: 1,
    overflow: 'auto',
    padding: 24,
  },
  loadingState: baseStyles.loadingState,
  spinner: baseStyles.spinner,
  errorState: baseStyles.errorState,
  searchContainer: baseStyles.searchContainer,
  searchWrapper: {
    ...baseStyles.searchWrapper,
    backgroundColor: '#f5f5f7',
    border: 'none',
  },
  searchIcon: baseStyles.searchIcon,
  searchInput: baseStyles.searchInput,
  appInfo: {
    display: 'flex',
    alignItems: 'center',
    gap: 16,
    padding: 16,
    backgroundColor: '#f5f5f7',
    borderRadius: 12,
    marginBottom: 24,
  },
  appIcon: baseStyles.appIcon,
  appIconImg: baseStyles.appIconImg,
  appMeta: baseStyles.appMeta,
  appVersion: baseStyles.appVersion,
  appTrain: baseStyles.appTrain,
  footer: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: 12,
    padding: '16px 24px',
    borderTop: '1px solid rgba(0, 0, 0, 0.08)',
    backgroundColor: '#fafafa',
  },
  cancelButton: {
    padding: '10px 20px',
    fontSize: 14,
    fontWeight: 500,
    color: '#1d1d1f',
    backgroundColor: '#ffffff',
    border: '1px solid rgba(0, 0, 0, 0.12)',
    borderRadius: 8,
    cursor: 'pointer',
    fontFamily: SF_PRO_TEXT,
    transition: 'all 0.2s ease',
  },
  submitButton: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '10px 24px',
    fontSize: 14,
    fontWeight: 600,
    color: '#ffffff',
    backgroundColor: '#0071e3',
    border: 'none',
    borderRadius: 8,
    cursor: 'pointer',
    fontFamily: SF_PRO_TEXT,
    transition: 'all 0.2s ease',
  },
  submitButtonDisabled: baseStyles.submitButtonDisabled,
  buttonSpinner: baseStyles.buttonSpinner,
};

// ---------------------------------------------------------------------------
// Shared field styles (used by FormField.tsx)
// ---------------------------------------------------------------------------

export const fieldStyles = {
  formGroup: baseStyles.formGroup,
  label: baseStyles.label,
  required: baseStyles.required,
  fieldDescription: baseStyles.fieldDescription,
  fieldHint: baseStyles.fieldHint,
  input: baseStyles.input,
  inputDisabled: baseStyles.inputDisabled,
  inputError: baseStyles.inputError,
  select: baseStyles.select,
  selectError: baseStyles.selectError,
  checkboxLabel: baseStyles.checkboxLabel,
  checkbox: baseStyles.checkbox,
  sectionTitleOutside: baseStyles.sectionTitleOutside,
  sectionFields: baseStyles.sectionFields,
  listContainer: baseStyles.listContainer,
  listEmpty: baseStyles.listEmpty,
  listItem: baseStyles.listItem,
  listItemContent: baseStyles.listItemContent,
  listItemField: baseStyles.listItemField,
  listItemLabel: baseStyles.listItemLabel,
  listItemSimple: baseStyles.listItemSimple,
  listItemInput: baseStyles.listItemInput,
  listItemDelete: baseStyles.listItemDelete,
  listAddButton: baseStyles.listAddButton,
  dictContainer: baseStyles.dictContainer,
  nestedFormGroup: baseStyles.nestedFormGroup,
  nestedFormGroupError: baseStyles.nestedFormGroupError,
  nestedLabel: baseStyles.nestedLabel,
  nestedDescription: baseStyles.nestedDescription,
  // Pool warning banner
  poolWarningBanner: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    padding: '14px 16px',
    backgroundColor: '#fff8e6',
    border: '1px solid #ffcc00',
    borderRadius: 10,
    marginBottom: 20,
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  poolWarningContent: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 2,
  },
  poolWarningHint: {
    fontSize: 12,
    color: '#86868b',
    fontFamily: SF_PRO_TEXT,
  },
};
